POST http://localhost:3333/polls HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "title": "Qual o melhor framework node",
  "options": ["Express", "Fastify", "NestJS", "HapiJS"]
}

###

GET http://localhost:3333/polls/9b7f7de7-076e-4260-b9d4-47ccca180c50 HTTP/1.1
Host: localhost:3333


###

POST http://localhost:3333/polls/9b7f7de7-076e-4260-b9d4-47ccca180c50/votes HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "pollOptionId": "1eb95991-9576-4e42-a38e-e028c6bbb6e9"
}
